apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "janus-gateway.fullname" . }}
  labels:
    {{- include "janus-gateway.labels" . | nindent 4 }}
data:
  janus.jcfg: |
    general: {
      configs_folder = "/opt/janus/etc/janus"
      plugins_folder = "/opt/janus/lib/janus/plugins"
      transports_folder = "/opt/janus/lib/janus/transports"
      events_folder = "/opt/janus/lib/janus/events"
      loggers_folder = "/opt/janus/lib/janus/loggers"
      debug_level = 4
      admin_secret = "janusoverlord"
      protected_folders = [
        "/bin",
        "/boot",
        "/dev",
        "/etc",
        "/initrd",
        "/lib",
        "/lib32",
        "/lib64",
        "/proc",
        "/sbin",
        "/sys",
        "/usr",
        "/var",
        "/opt/janus/bin",
        "/opt/janus/etc",
        "/opt/janus/include",
        "/opt/janus/lib",
        "/opt/janus/lib32",
        "/opt/janus/lib64",
        "/opt/janus/sbin"
      ]
    }
    nat: {
      stun_server = "{{ .Release.Name }}-coturn"
      stun_port = 3478
      nice_debug = false
      turn_server = "{{ .Release.Name }}-coturn"
      stun_port = 3478
      turn_user = "user"
      turn_pwd = "password"
      ice_ignore_list = "vmnet"
    }
    plugins: {}
    transports: {
      disable = "libjanus_http.so,libjanus_pfunix.so"
    }
    loggers: {}
    events: {}
  janus.transport.websockets.jcfg: |
    general: {
      json = "indented"
      ws = true
      ws_port = 8188
      wss = false
    }
    admin: {
      admin_ws = false
      admin_ws_port = 7188
      admin_wss = false
    }
    certificates: {}
  janus.plugin.audiobridge.jcfg: |
    general: {}
    room-1234: {
      description = "Demo Room"
      secret = "adminpwd"
      sampling_rate = 16000
      record = false
    }
  janus.plugin.echotest.jcfg: |
    general: {}
  janus.plugin.nosip.jcfg: |
    general: {
      rtp_port_range = "20000-40000"
    }
  janus.plugin.recordplay.jcfg: |
    general: {}
  janus.plugin.sip.jcfg: |
    general: {
      keepalive_interval = 120
      behind_nat = false
      register_ttl = 3600
      rtp_port_range = "20000-40000"
    }
  janus.plugin.streaming.jcfg: |
    general: {}
    rtp-sample: {
      type = "rtp"
      id = 1
      description = "Opus/VP8 live stream coming from external source"
      metadata = "You can use this metadata section to put any info you want!"
      audio = true
      video = true
      audioport = 5002
      audiopt = 111
      audiortpmap = "opus/48000/2"
      videoport = 5004
      videopt = 100
      videortpmap = "VP8/90000"
      secret = "adminpwd"
    }
    file-live-sample: {
      type = "live"
      id = 2
      description = "a-law file source (radio broadcast)"
      filename = "/opt/janus/share/janus/streams/radio.alaw"
      audio = true
      video = false
      secret = "adminpwd"
    }
    file-ondemand-sample: {
      type = "ondemand"
      id = 3
      description = "mu-law file source (music)"
      filename = "/opt/janus/share/janus/streams/music.mulaw"
      audio = true
      video = false
      secret = "adminpwd"
    }
  janus.plugin.textroom.jcfg: |
    general: {
      json = "indented"
    }
    room-1234: {
      description = "Demo Room"
      secret = "adminpwd"
    }
  janus.plugin.videocall.jcfg: |
    general: {}
  janus.plugin.videoroom.jcfg: |
    general: {}
    room-1234: {
      description = "Demo Room"
      secret = "adminpwd"
      publishers = 6
      bitrate = 128000
      fir_freq = 10
      record = false
    }
    room-5678: {
      description = "VP9-SVC Demo Room"
      secret = "adminpwd"
      publishers = 6
      bitrate = 512000
      fir_freq = 10
      videocodec = "vp9"
      video_svc = true
    }
  janus.plugin.voicemail.jcfg: |
    general: {}
  janus.eventhandler.gelfevh.jcfg: |
    general: {
      enabled = false
      events = "all"
      backend = "your.graylog.server"
      port = "12201"
      protocol = "tcp"
      max_message_len = 1024
    }
  janus.eventhandler.sampleevh.jcfg: |
    general: {
      enabled = false
      events = "all"
      grouping = true
      json = "indented"
      backend = "http://your.webserver.here/and/a/path"
    }
  janus.eventhandler.wsevh.jcfg: |
    general: {
      enabled = false
      events = "all"
      grouping = true
      json = "indented"
      backend = "ws://your.websocket.here"
    }
  janus-sentinel.yml: |+
    general:
      daemonize: false
    janus:
      server_ip: "127.0.0.1"
      ws_port: 8188
      admin_ws_port: 0
      pingpong_interval: 5
      statistic_interval: 10
      request_timeout: 10
      hwm_threshold: 1
      admin_secret: ""
    proc_watcher:
      cmdline: ""
      error_restart_interval: 10
      poll_interval: 1
    log:
      log_to_stdout: true
      debug_level: "DEBUG"
      log_file_size: 10485760
      log_file_rotate: 10
    admin_api:
      json: "indented"
      http_listen: "0.0.0.0:8200"
    posters:
      - post_type: "http"
        name: ""
        post_urls: ["http://{{ include "janus-proxy.fullname" . }}:8100/sentinel_callback"]
        expire: 60
        http_timeout: 10
