apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus-gateway
spec:
  selector:
    matchLabels:
      app: janus-gateway
  replicas: {{ .Values.janusGateway.replicas }}
  template:
    metadata:
      labels:
        app: janus-gateway
    spec:
      containers:
        - image: "{{ .Values.janusGateway.image.repository }}:{{ .Values.janusGateway.image.tag }}"
          imagePullPolicy: {{ .Values.janusGateway.image.pullPolicy }}
          name: janus-gateway
          resources:
            requests:
              cpu: 4
              memory: 8G
          ports:
            - containerPort: 8200
            - containerPort: 8188
          volumeMounts:
            - name: janus-sentinel
              mountPath: /opt/janus-cloud/conf/janus-sentinel.yml
              subPath: janus-sentinel.yml
            - name: janus
              mountPath: /opt/janus/etc/janus/janus.jcfg
              subPath: janus.jcfg
      volumes:
        - name: janus-sentinel
          configMap:
            name: janus-gateway
            items:
              - key: janus-sentinel.yml
                path: janus-sentinel.yml
        - name: janus
          configMap:
            name: janus-gateway
            items:
              - key: janus.jcfg
                path: janus.jcfg
