{{- if .Values.serviceAccount.janusProxy.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "janus-proxy.serviceAccountName" . }}
  labels:
    {{- include "janus-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.janusProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
