apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus-proxy.fullname" . }}
  labels:
    {{- include "janus-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8288
      protocol: TCP
      name: ws
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: http
  selector:
    {{- include "janus-proxy.selectorLabels" . | nindent 4 }}
