apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus-gateway
  namespace: {{ .Values.janusGateway.namespace }}
spec:
  selector:
    matchLabels:
      app: janus-gateway
  replicas: {{ .Values.janusGateway.replicas }}
  template:
    metadata:
      labels:
        app: janus-gateway
    spec:
      {{- with .Values.janusGateway.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.janusGateway.image.repository }}:{{ .Values.janusGateway.image.tag }}"
          imagePullPolicy: {{ .Values.janusGateway.image.pullPolicy }}
          name: janus-gateway
          command:
          {{- range .Values.janusGateway.command }}
            - "{{ . }}"
          {{- end }}
          resources:
            requests:
              cpu: 2
              memory: 4G
          ports:
            - containerPort: 8188
          volumeMounts:
            - name: janus-gateway
              mountPath: /opt/janus/etc/janus
        - image: "{{ .Values.janusSentinel.image.repository }}:{{ .Values.janusSentinel.image.tag }}"
          imagePullPolicy: {{ .Values.janusSentinel.image.pullPolicy }}
          name: janus-sentinel
          command:
            - janus-sentinel
          resources:
            requests:
              cpu: 1
              memory: 2G
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: janus-sentinel
              mountPath: /opt/janus-cloud/conf/janus-sentinel.yml
              subPath: janus-sentinel.yml
      volumes:
        - name: janus-sentinel
          configMap:
            name: janus-gateway
            items:
              - key: janus-sentinel.yml
                path: janus-sentinel.yml
        - name: janus-gateway
          configMap:
            name: janus-gateway
