apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janus-gateway.fullname" . }}
  labels:
    {{- include "janus-gateway.labels" . | nindent 4 }}
data:
  janus.jcfg: {{ .Values.config.janus | b64enc }}
  janus.transport.websockets.jcfg: {{ .Values.config.janusTransport.websockets | b64enc }}
  janus.plugin.audiobridge.jcfg: {{ .Values.config.janusPlugin.audiobridge | b64enc }}
  janus.plugin.echotest.jcfg: {{ .Values.config.janusPlugin.echotest | b64enc }}
  janus.plugin.nosip.jcfg: {{ .Values.config.janusPlugin.nosip | b64enc }}
  janus.plugin.recordplay.jcfg: {{ .Values.config.janusPlugin.recordplay | b64enc }}
  janus.plugin.sip.jcfg: {{ .Values.config.janusPlugin.sip | b64enc }}
  janus.plugin.streaming.jcfg: {{ .Values.config.janusPlugin.streaming | b64enc }}
  janus.plugin.textroom.jcfg: {{ .Values.config.janusPlugin.textroom | b64enc }}
  janus.plugin.videocall.jcfg: {{ .Values.config.janusPlugin.videocall | b64enc }}
  janus.plugin.videoroom.jcfg: {{ .Values.config.janusPlugin.videoroom | b64enc }}
  janus.plugin.voicemail.jcfg: {{ .Values.config.janusPlugin.voicemail | b64enc }}
  janus.eventhandler.gelfevh.jcfg: {{ .Values.config.janusEventhandler.gelfevh | b64enc }}
  janus.eventhandler.sampleevh.jcfg: {{ .Values.config.janusEventhandler.sampleevh | b64enc }}
  janus.eventhandler.wsevh.jcfg: {{ .Values.config.janusEventhandler.wsevh | b64enc }}
  janus-sentinel.yml: {{ .Values.config.janusSentinel | b64enc }}
