apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus-proxy
  namespace: {{ .Values.janusProxy.namespace }}
spec:
  selector:
    matchLabels:
      app: janus-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: janus-proxy
    spec:
      containers:
        - image: "{{ .Values.janusProxy.image.repository }}:{{ .Values.janusProxy.image.tag }}"
          imagePullPolicy: {{ .Values.janusProxy.image.pullPolicy }}
          name: janus-proxy
          command:
            - janus-proxy
          resources:
            requests:
              cpu: 2
              memory: 4G
          ports:
            - containerPort: 8288
            - containerPort: 8100
          volumeMounts:
            - name: janus-proxy
              mountPath: /opt/janus-cloud/conf
      volumes:
        - name: janus-proxy
          configMap:
            name: janus-proxy
