apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janus-proxy.fullname" . }}
  labels:
    {{- include "janus-proxy.labels" . | nindent 4 }}
data:
  janus-proxy.yml: {{ .Values.config.janusProxy | b64enc }}
  janus-proxy.plugin.p2pcall.yml: {{ .Values.config.janusProxyPlugin.p2pcall | b64enc }}
  janus-proxy.plugin.videocall.yml: {{ .Values.config.janusProxyPlugin.videocall | b64enc }}
  janus-proxy.plugin.videoroom.yml: {{ .Values.config.janusProxyPlugin.videoroom | b64enc }}
