apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janus-proxy.fullname" . }}
  labels:
    {{- include "janus-proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "janus-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "janus-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "janus-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "janus-proxy.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.janusCloud.repository }}:{{ .Values.image.janusCloud.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.janusCloud.pullPolicy }}
          command:
            - janus-proxy
          ports:
            - name: ws
              containerPort: 8288
              protocol: TCP
            - name: http
              containerPort: 8100
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: ws
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: ws
          volumeMounts:
            - name: janus-proxy-config
              mountPath: /opt/janus-cloud/conf
          resources:
            {{- toYaml .Values.resources.janusProxy | nindent 12 }}
      volumes:
        - name: janus-proxy-config
          configMap:
            name: {{ include "janus-proxy.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
