apiVersion: v1
kind: Service
metadata:
  name: janus-proxy
  {{- with .Values.janusProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - name: ws
      port: 80
      targetPort: 8288
      protocol: TCP
    - name: wss
      port: {{ .Values.janusProxy.port }}
      targetPort: 8288
      protocol: TCP
    - name: pong
      port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: janus-proxy
