{{- if .Values.serviceAccount.janusGateway.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "janus-gateway.serviceAccountName" . }}
  labels:
    {{- include "janus-gateway.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.janusGateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
