apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus-gateway
spec:
  selector:
    matchLabels:
      app: janus-gateway
  replicas: {{ .Values.janusGateway.replicas }}
  template:
    metadata:
      labels:
        app: janus-gateway
    spec:
      {{- with .Values.janusGateway.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.janusGateway.image.repository }}:{{ .Values.janusGateway.image.tag }}"
          imagePullPolicy: {{ .Values.janusGateway.image.pullPolicy }}
          name: janus-gateway
          command: {{ .Values.janusGateway.command }}
          resources:
            requests:
              cpu: 4
              memory: 8G
          ports:
            - containerPort: 8200
            - containerPort: 8188
          volumeMounts:
            - name: janus-sentinel
              mountPath: /opt/janus-cloud/conf/janus-sentinel.yml
              subPath: janus-sentinel.yml
            - name: janus-gateway
              mountPath: /opt/janus/etc/janus
      volumes:
        - name: janus-sentinel
          configMap:
            name: janus-gateway
            items:
              - key: janus-sentinel.yml
                path: janus-sentinel.yml
        - name: janus-gateway
          configMap:
            name: janus-gateway
