apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "janus-gateway.fullname" . }}
  labels:
    {{- include "janus-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "janus-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "janus-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "janus-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "janus-gateway.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.janusGateway.repository }}:{{ .Values.image.janusGateway.tag }}"
          imagePullPolicy: {{ .Values.image.janusGateway.pullPolicy }}
          ports:
            - name: ws
              containerPort: 8188
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: ws
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: ws
          volumeMounts:
            - name: janus-gateway-config
              mountPath: /opt/janus/etc/janus
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: janus-sentinel
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.janusCloud.repository }}:{{ .Values.image.janusCloud.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.janusCloud.pullPolicy }}
          command:
            - janus-sentinel
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: janus-sentinel-config
              mountPath: /opt/janus-cloud/conf/janus-sentinel.yml
              subPath: janus-sentinel.yml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: janus-gateway-config
          configMap:
            name: {{ include "janus-gateway.fullname" . }}
        - name: janus-sentinel-config
          configMap:
            name: {{ include "janus-gateway.fullname" . }}
            items:
              - key: janus-sentinel.yml
                path: janus-sentinel.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
